In [14]:
import pandas as pd
import os

In [15]:
options=pd.read_excel('Graduation Project (Responses).xlsx')

In [16]:
options

,Timestamp,Name,Text,Deepfake,Ai generated
0,2023-12-20 21:20:04.560,الاستااااااااااااذ محمد عبدالدايم,3,1,2
1,2023-12-20 21:30:15.204,H for Hondaaaaaaaaaaaaaaaaaaa,3,2,1
2,2023-12-20 22:31:48.555,أ.م زياد,1,2,3
3,2023-12-21 02:13:31.389,Abdalla Mohammed,2,1,3
4,2023-12-21 16:50:01.012,روان,3,2,1
5,2023-12-21 16:57:16.363,reham,1,3,2
6,2023-12-21 18:56:37.340,عمك,1,3,2

In [17]:
import pandas as pd

# Assuming 'options' is your DataFrame
deepfake = options[options['Deepfake'] == 1]
ai = options[options['Ai generated'] == 1]
text = options[options['Text'] == 1]
# Display the filtered DataFrame

ai.head()

,Timestamp,Name,Text,Deepfake,Ai generated
1,2023-12-20 21:30:15.204,H for Hondaaaaaaaaaaaaaaaaaaa,3,2,1
4,2023-12-21 16:50:01.012,روان,3,2,1

## Text

In [18]:
text.head()

                Timestamp       Name  Text  Deepfake  Ai generated
2 2023-12-20 22:31:48.555  أ.م زياد      1         2             3
5 2023-12-21 16:57:16.363     reham      1         3             2
6 2023-12-21 18:56:37.340       عمك      1         3             2

## Deepfake

In [19]:
deepfake.head()

,Timestamp,Name,Text,Deepfake,Ai generated
0,2023-12-20 21:20:04.560,الاستااااااااااااذ محمد عبدالدايم,3,1,2
3,2023-12-21 02:13:31.389,Abdalla Mohammed,2,1,3

In [20]:

def create_folder(folder_path):
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        print(f"Folder '{folder_path}' created.")
    else:
        print(f"Folder '{folder_path}' already exists.")

def create_readme_in_folders(folder_path,file):
    # get member name
    memeberName=folder_path.split('/')[1]

    readme_path = os.path.join(folder_path,file)
    # os.remove(readme_path)
    # return
    with open(readme_path, "w") as readme_file:
        # Write content to the README file
        readme_file.write(f"# Welcome to {memeberName}'s Task Folder")
        print(f"README.md created successfully in '{readme_path}'.")


folders_to_create = ["Tasks/romani","Tasks/Sara","Tasks/Ziad","Tasks/Abdalah","Tasks/Rawan","Tasks/Mohammed","Tasks/Mohaned","Tasks/Reham","Tasks/Ahmed"]

for folder_path in folders_to_create:
    #create folders
    # create_folder(folder_path)
    
    #create README 
    file= "README.md"
    # create_readme_in_folders(folder_path,file)